
ALTER TABLE `USER_CHECKLIST_MASTER` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `USER_COLLEGE_MASTER` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `USER_STATUS_MASTER` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `USER_SCHOOL_MASTER` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `USER_LAW_COLLEGE_MASTER` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `USER_LAW_ADDRESS_MASTER` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `employmentform` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `enrollment_master` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `userbasicdetailsmaster` ADD `user_id` INT(11) NULL AFTER `ID`;

ALTER TABLE `userotherinformation` ADD `user_id` INT(11) NULL AFTER `ID`;